#!/bin/bash

output=$(cat)

regex="make: Nothing to be done for '(.*)'"
if [[ "$output" =~ $regex ]]; then

    # If target is a directory
    if [[ -d "${BASH_REMATCH[1]}" ]]; then
        echo "Cannot run \`make\` on a directory. Did you mean to \`cd ${BASH_REMATCH[1]}\` first?"
        exit
    fi

    # If target ends with .c
    if [[ "${BASH_REMATCH[1]}" == *?.c ]]; then
        base="${BASH_REMATCH[1]%.c}"
        if [[ -n "$base" && ! -d "$base" ]]; then
            echo "Did you mean to \`make ${base}\`?"
            exit
        fi
    fi

fi

regex="No rule to make target '(.*)'"
if [[ "$output" =~ $regex ]]; then

    # If no .c file for target
    c="${BASH_REMATCH[1]}.c"
    if [[ ! -f "$c" ]]; then

        # Search recursively for .c file
        path=$(_search "$c")
        echo -n "There isn't a file called \`${c}\` in your current directory. You are in \`$(basename "$PWD")\`."
        if [[ ! -z "$path" ]]; then
            echo " Did you mean to \`cd $path\` first?"
        else
            echo
        fi
        exit
    fi
fi
