#!/bin/bash

. /opt/cs50/lib/cli

output=$(cat)

regex="AttributeError: module 'cs50' has no attribute '(get_(float|int|string)|SQL)'$"
if [[ "$output" =~ $regex ]]; then
    if [[ -f cs50.py ]]; then
        echo "You have a file called \`cs50.py\` that is \"shadowing\" CS50's own. Best to rename that file with \`mv\`."
        exit
    fi
fi

regex='^\s*(import string\s*$|from\s+string\s+import\s+)'
if echo "$output" | grep -Pq "$regex"; then
    if [[ -f string.py ]]; then
        echo "You have a file called \`string.py\` that is \"shadowing\" Python's own. Best to rename that file with \`mv\`."
        exit
    fi
fi

regex="python: can't open file '(.*\.py)': \[Errno 2\] No such file or directory"
if [[ "$output" =~ $regex ]]; then

    # Relative path from $PWD
    path=$(realpath --relative-to=. "${BASH_REMATCH[1]}")

    # If .py is in $PWD
    if [[ -n "$path" && "$path" == $(basename "$path") ]]; then
        dir=$(_find -type f "$path")
        echo -n "There isn't a file called \`$path\` in your current directory."
        if [[ ! -z "$dir" ]]; then
            echo " Did you mean to \`cd $dir\` first?"
        else
            echo
        fi
        exit
    fi
fi
